#ifndef TEST_H_INCLUDED
#define TEST_H_INCLUDED

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "TDACentroLogistico.h"

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE REPARTOS CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr crearListaRepartosPorDefectoConLista();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE PAQUETES CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr crearListaPaquetesGenerico();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE PERSONAS CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr crearListaPersonasGenerica();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE CLIENTES CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr clientesGenericos();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE CHOFERES CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr choferesGenericos();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UNA LISTA DE VEHICULOS CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A LISTA
ListaPtr crearListaVehiculosGenerico();

///OPERACION: CREACION
///PRECONDICION: LA LISTA RECEPTORA DEBE HABER SIDO DECLARADA
///POSTCONDICION: CREA UN CENTRO LOGISTICO CON DATOS POR DEFECTO
///PARAMETROS: NINGUNO
///DEVUELVE: PUNTERO A CENTRO LOGISTICO
CentroLogisticoPtr crearCentroLogisticoDefecto();


#endif // TEST_H_INCLUDED
